# Site
repository: EndlessKn0t/EndlessKn0t.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shreevatsa Bhagwat
title: Student at IIT Tirupati
email: shreevatsabhagwat@gmail.com or ee21b047@iittp.ac.in
website: https://endlesskn0t.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  endlesskn0t
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: va.t5a
linkedin_username: shreevatsa-bhagwat
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/passportphoto.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shreevatsa and I'm an Elctrical Engineering student at IIT Tirupati. I am interested in Computer Architecture.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Sensor Validation, Data Imputation, and Performance Prediction of Aero Engines Using Machine Learning Techniques
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          <mark>Abstract:</mark>The project involved working on the sensor data from aero gas turbine engines to determine faults and predict the performance of the engine. Machine learning models were used to analyse the data using various parameters. Interrelation between different parameters were analysed for obtaining a robust model.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Intern
        link: https://www.linkedin.com/company/gas-turbine-research-establishment-drdo/?originalSubdomain=in
        link_text: GTRE, DRDO
        #sub_title: Senior Network System Administrator
        caption: May 2023 - Jul 2023
        quote: >
          Guide : Mr. Vikas, Scientist ’E’, GTRE, DRDO, Bengaluru
        description: I have worked in the Instrumentation and Control Group of GTRE, DRDO. The areas covered are Data Science, Machine Learning, Sensing, Instrumentation and Measurement.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IIT Tirupati
        caption: 2021 - 2025
        sub_title: B.Tech Electrical Engineering
        quote: |
         My time at IIT Tirupati is very valuable. I participated in various academic and co-curricular activitites at the institution. I held various positions such as 
         - Coordinator of Health Issues division at NSS IIT Tirupati 
         - Core Member in Debate club and Quiz club
         - Coordinator at Marketing Commitee for the annual techno-cultural fest,  Tirutsava. 

                  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Reading Historical Fiction and Sci-Fi books
      - Playing strategy games
      - Trekking
      - Quizzing
      - Debating

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
